package io.github.scalats.python

import java.io.{ File, PrintStream }

import scala.io.Source.fromFile

import io.github.scalats.ast.Declaration
import io.github.scalats.core.Internals.ListSet
import io.github.scalats.core.Settings

final class PythonFilePrinterSpec extends org.specs2.mutable.Specification {
  "Python file printer".title

  sequential

  def withTempDir[T](f: File => T): T = {
    val tmp = File.createTempFile("PythonFilePrinterSpec", "")
    tmp.delete()
    tmp.mkdirs()

    try {
      f(tmp)
    } finally {
      def deleteRec(d: File): Unit = {
        Option(d.listFiles).foreach(_.foreach(deleteRec))
        val _ = d.delete()
      }

      deleteRec(tmp)
    }
  }

  "prelude" should {
    "use Python comments when configured on the printer instance" in
      withTempDir { outDir =>
        val printer = new PythonFilePrinter(outDir)
        printer.configurePrelude(
          "# Generated by ScalaTS: https://scala-ts.github.io/scala-ts/"
        )

        val conf = Settings()

        withPrinter(
          printer(
            conf,
            Declaration.Interface,
            ListSet(),
            "Foo",
            ListSet.empty
          )
        ) { out =>
          out.println("class Foo: pass")
          out.flush()
        }

        val content = fromFile(new File(outDir, "foo.py")).mkString

        content must startWith(
          "# Generated by ScalaTS: https://scala-ts.github.io/scala-ts/"
        )
        content must not contain ("// Generated by ScalaTS")
      }
  }

  private def withPrinter[T](p: => PrintStream)(f: PrintStream => T): T = {
    var w: PrintStream = null

    try {
      w = p
      f(w)
    } finally {
      if (w != null) {
        w.close()
      }
    }
  }
}
