package io.github.scalats.plugins

import java.io.{ File, PrintStream }

import scala.io.Source.fromFile

import io.github.scalats.ast.Declaration
import io.github.scalats.core.Internals.ListSet
import io.github.scalats.core.Settings

/**
 * Minimal, deterministic reproduction of the prelude cross-language leak.
 *
 * == Reported symptom ==
 * TypeScript files sometimes start with a Python prelude (`# …`) or the
 * opposite, about half of the time when compiling with sbt.
 *
 * == Root cause (before the fix) ==
 *  1. The prelude text was written to a mutable file
 *     (`target/scala-ts-prelude.tmp`).
 *  2. Its location was published through the JVM-global system property
 *     `scala-ts.printer.prelude-url` (via `-P:scalats:sys.…` scalac options).
 *  3. `BasePrinter.printPrelude` re-read that file on every call.
 *
 * Any concurrent compilation (two sbt subprojects, a TS module and a Python
 * module, or even two waves in the same sbt daemon) could overwrite either the
 * property or the file while another printer was reading it.
 *
 * == These tests ==
 * They deliberately use the legacy lookup path (printer ''without''
 * `configurePrelude`) and assert the ''buggy'' outcome so maintainers can see
 * exactly what went wrong. The fix passes the prelude through
 * `Configuration.printerPrelude` and caches it per printer instance; see the
 * last example group.
 *
 * To observe the original flaky ~50% behaviour end-to-end, revert the fix and
 * run the scripted test `sbt-scala-ts-python/prelude-isolation`.
 */
final class PreludeRaceReproductionSpec
    extends org.specs2.mutable.Specification {
  "Prelude race reproduction (legacy mechanism)".title

  sequential

  def withTempDir[T](f: File => T): T = {
    val tmp = File.createTempFile("PreludeRaceReproductionSpec", "")
    tmp.delete()
    tmp.mkdirs()

    try {
      f(tmp)
    } finally {
      def deleteRec(d: File): Unit = {
        Option(d.listFiles).foreach(_.foreach(deleteRec))
        val _ = d.delete()
      }

      deleteRec(tmp)
    }
  }

  def writePreludeFile(f: File, content: String): Unit = {
    val out = new PrintStream(f)
    out.print(content)
    out.close()
  }

  def emitTypeScript(
      printer: FilePrinter,
      typeName: String
    ): Unit =
    withPrinter(
      printer(
        Settings(),
        Declaration.Interface,
        ListSet(),
        typeName,
        ListSet.empty
      )
    ) { out =>
      out.println(s"export type ${typeName} = string")
      out.flush()
    }

  def withSysProp[T](key: String, value: String)(f: => T): T =
    try {
      sys.props.put(key, value)
      f
    } finally {
      sys.props.remove(key)
      ()
    }

  "parallel sbt subprojects" should {
    """
    |reproduce the leak when a Python compilation overwrites the global
    |`scala-ts.printer.prelude-url` property before TypeScript reads it
    """.stripMargin in withTempDir { outDir =>
      val tsPrelude = File.createTempFile("PreludeRaceReproductionSpec", ".ts")
      val pyPrelude = File.createTempFile("PreludeRaceReproductionSpec", ".py")

      tsPrelude.deleteOnExit()
      pyPrelude.deleteOnExit()

      writePreludeFile(tsPrelude, "// Generated by ScalaTS (TypeScript)\n")
      writePreludeFile(pyPrelude, "# Generated by ScalaTS (Python)\n")

      withSysProp(
        "scala-ts.printer.prelude-url",
        tsPrelude.toURI.toString
      ) {
        // TypeScript subproject: scalatsPrepare wrote `//` and set the property
        // to its own `target/scala-ts-prelude.tmp` …

        // … then the Python subproject running in parallel overwrote the single
        // JVM-global property (same key for every ScalaTS user in this sbt
        // process):
        sys.props.put(
          "scala-ts.printer.prelude-url",
          pyPrelude.toURI.toString
        )

        // TypeScript printer still uses the legacy global lookup (no fix):
        val printer = new FilePrinter(outDir)
        emitTypeScript(printer, "Leaked")

        val content = fromFile(new File(outDir, "Leaked.ts")).mkString

        // Bug: Python comment style in a `.ts` file.
        content must startWith("# Generated by ScalaTS (Python)")
        content must not contain ("// Generated by ScalaTS (TypeScript)")
      }
    }
  }

  "stale shared prelude file" should {
    """
    |reproduce the leak when `scalatsPrepare` has not rewritten the shared
    |`scala-ts-prelude.tmp` yet (or skipped) and it still contains Python text
    """.stripMargin in withTempDir { outDir =>
      val sharedPrelude =
        File.createTempFile("PreludeRaceReproductionSpec", ".tmp")

      sharedPrelude.deleteOnExit()

      // Leftover from an earlier Python generation in the same `target/`.
      writePreludeFile(
        sharedPrelude,
        "# Generated by ScalaTS (Python)\n"
      )

      withSysProp(
        "scala-ts.printer.prelude-url",
        sharedPrelude.toURI.toString
      ) {
        // TypeScript `scalatsPrepare` would overwrite this with `// …` — not
        // simulated here to reproduce the read-before-write window.

        val printer = new FilePrinter(outDir)
        emitTypeScript(printer, "Stale")

        fromFile(new File(outDir, "Stale.ts")).mkString must startWith(
          "# Generated by ScalaTS (Python)"
        )
      }
    }
  }

  "fixed mechanism" should {
    """
    |keep the TypeScript prelude even when global state is corrupted afterwards
    """.stripMargin in withTempDir { outDir =>
      val pyPrelude = File.createTempFile("PreludeRaceReproductionSpec", ".py")

      pyPrelude.deleteOnExit()
      writePreludeFile(pyPrelude, "# Generated by ScalaTS (Python)\n")

      withSysProp(
        "scala-ts.printer.prelude-url",
        pyPrelude.toURI.toString
      ) {
        val printer = new FilePrinter(outDir)
        printer.configurePrelude("// Generated by ScalaTS (TypeScript)\n")

        sys.props.put(
          "scala-ts.printer.prelude-url",
          pyPrelude.toURI.toString
        )

        writePreludeFile(pyPrelude, "# Overwritten on disk too\n")

        emitTypeScript(printer, "Fixed")

        val content = fromFile(new File(outDir, "Fixed.ts")).mkString

        content must startWith("// Generated by ScalaTS (TypeScript)")
        content must not contain ("# Generated by ScalaTS (Python)")
        content must not contain ("# Overwritten on disk too")
      }
    }
  }

  private def withPrinter[T](p: => PrintStream)(f: PrintStream => T): T = {
    var w: PrintStream = null

    try {
      w = p
      f(w)
    } finally {
      if (w != null) {
        w.close()
      }
    }
  }
}
